---
title: "p8105_hw2_ng2696"
author: "Nihan Gencerliler"
date: "10/2/2019"
output: github_document
---

# Homework 2
```{r setup}
library(readxl)
library (ggplot2)
library(tidyverse)
```
## Problem 1

```{r}
mr_trash_wheel = read_excel("./p8105_hw2_ng2696_files/Trash-Wheel-Collection-Totals-8-6-19.xlsx",sheet="Mr. Trash Wheel", range="A2:N406") %>%
  janitor::clean_names() %>%
  drop_na() %>%
  mutate(sports_balls_integer=as.integer(sports_balls))
head(mr_trash_wheel)
```
```{r}
mr_trash_wheel_2017 = read_excel("./p8105_hw2_ng2696_files/Trash-Wheel-Collection-Totals-8-6-19.xlsx",sheet="2017 Precipitation",range="A2:B14") %>%
  mutate(year=2017)
mr_trash_wheel_2018 = read_excel("./p8105_hw2_ng2696_files/Trash-Wheel-Collection-Totals-8-6-19.xlsx",sheet="2018 Precipitation",range="A2:B14") %>%
  mutate(year=208)
mr_trash_wheel_monthly = 
  bind_rows(mr_trash_wheel_2017,mr_trash_wheel_2018)%>%
  janitor::clean_names() %>%
  mutate(month=month.name[month])
head(mr_trash_wheel_monthly)
```

## Problem 2

Read and clean pols_month:
```{r}
pols_month=read_csv("./p8105_hw2_ng2696_files/fivethirtyeight_datasets/pols-month.csv") %>%
separate(mon,c("year","month","day"),"-") %>%
  mutate(month=month.name[as.integer(month)]) %>%
  mutate(president=recode(prez_dem, `1` = "dem", `0` = "gop")) %>%
  select(-prez_dem,-prez_gop,-day)
head(pols_month)
```

Read and clean snp:
```{r}
snp=read_csv("./p8105_hw2_ng2696_files/fivethirtyeight_datasets/snp.csv") %>%
separate(date,c("month","day","year"),"/") %>%
  mutate(month_integer=as.integer(month),month=month.name[month_integer]) %>%
  arrange(year, month_integer) %>%
  select(year, month, close, -day, -month_integer) 

snp
```
Read and clean unemployment:
```{r}
unemployment=read_csv("./p8105_hw2_ng2696_files/fivethirtyeight_datasets/unemployment.csv") %>%
  pivot_longer(Jan:Dec,
               names_to="month",
               values_to="percent_unemployed") %>%
    mutate(month=recode(month, `Jan` = "January", `Feb` = "February",`Mar` = "March",`Apr` = "April",`May` = "May",`Jun` = "June",`Jul` = "July",`Aug` = "August",`Sep` = "September",`Oct` = "October",`Nov` = "November", `Dec`="December")) %>%
    janitor::clean_names() 
unemployment
```

Merge snp and pols_month:
```{r}
snp_pols_month=
left_join(snp, pols_month, by=c("year","month")) %>%
  mutate(year=as.integer(year))
snp_pols_month
```
Merge above dataset with unemployment:
```{r}
snp_pols_unemployment=
left_join(snp_pols_month, unemployment, by=c("year","month"))
snp_pols_unemployment
```
## Problem 3

Read and clean dataset:
```{r}
baby_names = read_csv("./p8105_hw2_ng2696_files/Popular_Baby_Names.csv") %>%
  janitor::clean_names() %>%
  distinct() %>%
  mutate(ethnicity=recode(ethnicity,`ASIAN AND PACIFIC ISLANDER` = "Asian and Pacific Islander", `BLACK NON HISPANIC` = "Black Non-hispanic",`HISPANIC` = "Hispanic", `WHITE NON HISPANIC` = "White Non-hispanic",`ASIAN AND PACI` = "Asian and Pacific Islander", `BLACK NON HISP` = "Black Non-hispanic",`WHITE NON HISP` = "White Non-hispanic"),gender=recode(gender, `FEMALE` = "Female", `MALE` = "Male"),childs_first_name=str_to_title(childs_first_name))
#using unique to check categorical predictors
unique(pull(baby_names,ethnicity))
unique(pull(baby_names,gender))
```

Create table showing popularity of Olivia only:
```{r}
olivia=
  filter(baby_names,childs_first_name=="Olivia") %>%
  mutate(rank=as.integer(rank))%>%
  pivot_wider(names_from="year_of_birth", values_from="rank") %>%
  select(-gender,-count,-childs_first_name) %>%
  group_by(ethnicity) %>%
  summarise_each(funs(na.omit))
knitr::kable(olivia)
```

Create table of most popular male names:

```{r}
males=
  filter(baby_names,gender=="Male",rank==1) %>%
  mutate(year_of_birth=as.factor(year_of_birth))%>%
  pivot_wider(names_from="year_of_birth", values_from="childs_first_name") %>%
  select(-gender,-count,-rank)%>% group_by(ethnicity) %>%
  summarise_each(funs(na.omit))  

knitr::kable(males)
```


Scatterplot of male names:
```{r}
males_plot=
  filter(baby_names,gender=="Male",year_of_birth==2016,ethnicity=="White Non-hispanic")
ggplot(males_plot,aes(x=rank,y=count)) + geom_text(aes(label=childs_first_name), size=2)
```

